###
POST http://localhost:9200/user/create
Content-Type: application/json
Authorization: Basic admin admin

{
  "username": "testUser",
  "password": "Coding12#",
  "authority": "ROLE_APPUSER"
}

###
POST http://localhost:9200/user/create
Content-Type: application/json
Authorization: Basic admin admin

{
  "username": "testUser2",
  "password": "Coding12#",
  "authority": "ROLE_APPUSER"
}

###
PUT http://localhost:9200/user/edit/2
Content-Type: application/json
Authorization: Basic admin admin

{
  "username": "testUser_newName",
  "password": "Coding12#",
  "authority": "ROLE_VOLUNTEER"
}

###
GET http://localhost:9200/user/view
Authorization: Basic admin admin

###
DELETE http://localhost:9200/user/delete/3
Authorization: Basic admin admin

###
GET http://localhost:9200/user/view
Authorization: Basic admin admin



