server:
  port: 9200

spring:
  datasource:
    url: jdbc:mysql://localhost/appointment-management?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

application:
  admin:
    user:
      username: admin
      password: admin
      authorities: ROLE_ADMIN
  appuser:
    user:
      authorities: ROLE_APPUSER